services:
  - type: web
    name: testdjanago
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn testdjanago.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
