# Generated by Django 5.0.4 on 2025-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='img',
            field=models.ImageField(upload_to='comics/'),
        ),
    ]
